### ISSUE TITLE
Moving to fsprojects organization

### ISSUE THREAD

**Issue by vasily-kirichenko** [jack-pappas/ExtCore#41]
I think @jack-pappas has not had time for this project for recent months, https://github.com/jack-pappas/ExtCore/pull/32 was closed without merging, this is a very bad sign. 

I propose to move this project to fsprojects organization, move to Paket, add a project build script, and release version 1.0 after https://github.com/jack-pappas/ExtCore/pull/32 is merged.

@7sharp9 @dsyme @forki @enricosada @wallymathieu

**Comment by wallymathieu** [comment]
As long as there is someone who respects the vision of the project in charge of it, it should be fine.

**Comment by wallymathieu** [comment]
There is a lot of code in ExtCore, so it would probably be nice to have additional maintainers in order to help @jack-pappas.

**Comment by vasily-kirichenko** [comment]
@wallymathieu I'm not suggesting to change anything in the project vision, etc. I just suggest to resurrect it so other people could merge PRs and release the NuGet package.

**Comment by vasily-kirichenko** [comment]
@7sharp9 yes. I've ended up building a private package with #32 merged and use it. That's not good.

**Comment by wallymathieu** [comment]
Indeed, it would be nice to resurrect the project. It would be good to have people who shares @jack-pappas vision could be in charge.

**Comment by wallymathieu** [comment]
What do you think @jack-pappas ?

**Comment by jack-pappas** [comment]
I'd prefer not to move _ExtCore_ to fsprojects. I don't think the location of the project is the real issue here -- it's that I haven't had free time to work on _ExtCore_ in a long while, but I also haven't made it easy (or even possible, really) for others to help maintain the project.

I think if we fix the maintainability issues, we're probably in good shape for the future, right? I've written up some issues this morning for various maintenance tasks and created a new project for this repo to track them: https://github.com/jack-pappas/ExtCore/projects/1

Would you all mind taking a look at the issues I've created and commenting if you have thoughts to share?

**Comment by wallymathieu** [comment]
So, essentially it is that there is a single maintainer? But that could also be seen as a pro since it can keep the vision aligned.

**Comment by vasily-kirichenko** [comment]
I'm OK with not moving it if there is a way to publish packages via CI.

**Comment by wallymathieu** [comment]
@dsyme sounds like a good policy 👍
